include:
  - docker-compose-kafka.yaml

services:

  snowflake:
    container_name: "snowflake"
    image: localstack/snowflake
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - EXTRA_CORS_ALLOWED_ORIGINS=*
#      - DEBUG=1
#      - SF_LOG=trace
    volumes:
      - "./volume-snowflake:/var/lib/localstack"